### ISSUE TITLE
Sibling dependencies are not supported

### ISSUE THREAD

**Issue by polkovnikov-ph** [browserify/wzrd.in#180] opened 2017-09-07 11:30 UTC
```
---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: b10b64c0-93bf-11e7-a2d2-1b06f612731f )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react-dom' from '/tmp/react-draggable11787-18278-1yququ5/node_modules/react-draggable/dist'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

dirPath: /tmp/react-draggable11787-18278-1yququ5


------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```

**Comment by jfhbrook** [comment] 2017-09-07 14:16
Duplicate of https://github.com/browserify/wzrd.in/issues/130

**Closed by jfhbrook** 2017-09-07 14:16 UTC
