### ISSUE TITLE
Certain URL crashes the server

### ISSUE THREAD

**Issue by AgeOfMarcus** [browserify/wzrd.in#200] opened 2019-08-09 18:34 UTC
I can't tell you the logs, but I stumbled upon an error that seems to appear when visiting this uri: 
`/debug-standalone/antd@latest'`

It appears to crash the entire service on some sites hosting but on others just gives an error. PS: the site that this crashed fully was hosted on heroku if that makes a difference.

**Comment by PlNG** [comment] 2019-09-21 21:05
Duplicate of #189

**Closed as completed** 2019-09-29 10:11 UTC
